// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaj_6we5-LIzA0FZn4ruOruUoUPM6uD3g',
    appId: '1:624255778570:web:06e90cbc5a214bc98a84f3',
    messagingSenderId: '624255778570',
    projectId: 'ecosync-app',
    authDomain: 'ecosync-app.firebaseapp.com',
    storageBucket: 'ecosync-app.firebasestorage.app',
    measurementId: 'G-WHCQSDM1XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7fvMoppBsM1vK5Yrkv2Z2R9H2icG7__M',
    appId: '1:624255778570:android:d9b47884c6bcee728a84f3',
    messagingSenderId: '624255778570',
    projectId: 'ecosync-app',
    storageBucket: 'ecosync-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGT5rEfHNl6ZIQWHKT0BGtZ9HlNVT6f5E',
    appId: '1:624255778570:ios:b71b87799d785d738a84f3',
    messagingSenderId: '624255778570',
    projectId: 'ecosync-app',
    storageBucket: 'ecosync-app.firebasestorage.app',
    iosBundleId: 'com.example.ecosyncgh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGT5rEfHNl6ZIQWHKT0BGtZ9HlNVT6f5E',
    appId: '1:624255778570:ios:b71b87799d785d738a84f3',
    messagingSenderId: '624255778570',
    projectId: 'ecosync-app',
    storageBucket: 'ecosync-app.firebasestorage.app',
    iosBundleId: 'com.example.ecosyncgh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaj_6we5-LIzA0FZn4ruOruUoUPM6uD3g',
    appId: '1:624255778570:web:0930c0a340ed57da8a84f3',
    messagingSenderId: '624255778570',
    projectId: 'ecosync-app',
    authDomain: 'ecosync-app.firebaseapp.com',
    storageBucket: 'ecosync-app.firebasestorage.app',
    measurementId: 'G-17RLPZZ3SD',
  );
}
